from os import environ

AUTH0_DOMAIN = environ.get("AUTH0_DOMAIN")
AUTH0_AUDIENCE = environ.get("AUTH0_AUDIENCE")
AUTH0_CLIENT_ID = environ.get("AUTH0_CLIENT_ID")
AUTH0_CLIENT_SECRET = environ.get("AUTH0_CLIENT_SECRET")
AUTH0_CALLBACK_URI = environ.get("AUTH0_CALLBACK_URI")
DATABASE_URI = environ.get("DATABASE_URI")
CAHCE_REDIS_URL = environ.get("CACHE_REDIS_URL")
