"""empty message

Revision ID: e93506e96cdb
Revises:
Create Date: 2020-07-25 14:53:53.735017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93506e96cdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    subseries_table = op.create_table('subseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('num_books', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    books_table = op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('book_number', sa.Integer(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('subseries_number', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('subseries_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subseries_id'], ['subseries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(subseries_table, subseries)
    op.bulk_insert(books_table, books)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('subseries')
    # ### end Alembic commands ###


subseries = [
    {
        "title": "Rincewind",
        "num_books": 8
    }, {
        "title": "Witches",
        "num_books": 6
    }, {
        "title": "Death",
        "num_books": 5
    }, {
        "title": "Djelibeybi",
        "num_books": 1
    }, {
        "title": "City Watch",
        "num_books": 8
    }, {
        "title": "Industrial Revolution",
        "num_books": 3
    }, {
        "title": "Omnia",
        "num_books": 1
    }, {
        "title": "Überwald",
        "num_books": 1
    }, {
        "title": "Moist von Lipwig",
        "num_books": 3
    }, {
        "title": "Tiffany Aching",
        "num_books": 5
    }
]
books = [
    {
        "book_number": 1,
        "subseries_id": 1,
        "subseries_number": 1,
        "title": "The Color of Magic",
        "year": 1983,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1407111017l/34497._SX98_.jpg",
        "score": 3.99,
        "pages": 228,
        "isbn": "0060855924"
    },
    {
        "book_number": 4,
        "subseries_id": 3,
        "subseries_number": 1,
        "title": "Mort",
        "year": 1987,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 4.24,
        "pages": 243,
        "isbn": "0061020680"
    },
    {
        "book_number": 8,
        "subseries_id": 5,
        "subseries_number": 1,
        "title": "Guards! Guards!",
        "year": 1989,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1431127356l/64216._SX98_.jpg",
        "score": 4.33,
        "pages": 376,
        "isbn": "0061020648"
    },
    {
        "book_number": 3,
        "subseries_id": 2,
        "subseries_number": 1,
        "title": "Equal Rites",
        "year": 1987,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1407706800l/34507._SX98_.jpg",
        "score": 4.03,
        "pages": 228,
        "isbn": "0060855908"
    },
    {
        "book_number": 2,
        "subseries_id": 1,
        "subseries_number": 2,
        "title": "The Light Fantastic",
        "year": 1986,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 3.98,
        "pages": 277,
        "isbn": "0061020702"
    },
    {
        "book_number": 33,
        "subseries_id": 9,
        "subseries_number": 1,
        "title": "Going Postal",
        "year": 2004,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 4.39,
        "pages": 394,
        "isbn": "0060502932"
    },
    {
        "book_number": 13,
        "subseries_id": 7,
        "subseries_number": 1,
        "title": "Small Gods",
        "year": 1992,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 4.30,
        "pages": 400,
        "isbn": "0552152978"
    },
    {
        "book_number": 30,
        "subseries_id": 10,
        "subseries_number": 1,
        "title": "The Wee Free Men",
        "year": 2003,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1443764106l/34494._SY160_.jpg",
        "score": 4.27,
        "pages": 375,
        "isbn": "0060012382"
    },
    {
        "book_number": 15,
        "subseries_id": 5,
        "subseries_number": 2,
        "title": "Men at Arms",
        "year": 1993,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 4.38,
        "pages": 377,
        "isbn": "0061092193"
    },
    {
        "book_number": 11,
        "subseries_id": 3,
        "subseries_number": 2,
        "title": "Reaper Man",
        "year": 1991,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1389211958l/34517._SX98_.jpg",
        "score": 4.28,
        "pages": 352,
        "isbn": "0552152951"
    },
    {
        "book_number": 6,
        "subseries_id": 2,
        "subseries_number": 2,
        "title": "Wyrd Sisters",
        "year": 1988,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1275974472l/34504._SX98_.jpg",
        "score": 4.13,
        "pages": 265,
        "isbn": "0061020664"
    },
    {
        "book_number": 12,
        "subseries_id": 2,
        "subseries_number": 3,
        "title": "Witches Abroad",
        "year": 1991,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1403326937l/2442._SX98_.jpg",
        "score": 4.22,
        "pages": 374,
        "isbn": "0061020613"
    },
    {
        "book_number": 29,
        "subseries_id": 5,
        "subseries_number": 6,
        "title": "Night Watch",
        "year": 2002,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1320518310l/47989._SX98_.jpg",
        "score": 4.50,
        "pages": 480,
        "isbn": "055215430X"
    },
    {
        "book_number": 10,
        "subseries_id": 6,
        "subseries_number": 1,
        "title": "Moving Pictures",
        "year": 1990,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1320456553l/34510._SX98_.jpg",
        "score": 3.94,
        "pages": 396,
        "isbn": "0552152943"
    },
    {
        "book_number": 19,
        "subseries_id": 5,
        "subseries_number": 3,
        "title": "Feet of Clay",
        "year": 1996,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1320490628l/34527._SX98_.jpg",
        "score": 4.29,
        "pages": 411,
        "isbn": "0552153257"
    },
    {
        "book_number": 7,
        "subseries_id": 4,
        "subseries_number": 1,
        "title": "Pyramids",
        "year": 1989,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 3.91,
        "pages": 341,
        "isbn": "0061020656"
    },
    {
        "book_number": 31,
        "subseries_id": 6,
        "subseries_number": 3,
        "title": "Monstrous Regiment",
        "year": 2003,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1375908503l/34511._SX98_.jpg",
        "score": 4.21,
        "pages": 496,
        "isbn": "0385603401"
    },
    {
        "book_number": 26,
        "subseries_id": 3,
        "subseries_number": 5,
        "title": "Thief of Time",
        "year": 2001,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 4.26,
        "pages": 378,
        "isbn": "0061031321"
    },
    {
        "book_number": 36,
        "subseries_id": 9,
        "subseries_number": 2,
        "title": "Making Money",
        "year": 2007,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 4.24,
        "pages": 394,
        "isbn": "0061161640"
    },
    {
        "book_number": 14,
        "subseries_id": 2,
        "subseries_number": 4,
        "title": "Lords and Ladies",
        "year": 1992,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1469186110l/34529._SX98_.jpg",
        "score": 4.17,
        "pages": 400,
        "isbn": "055215315X"
    },
    {
        "book_number": 9,
        "subseries_id": 1,
        "subseries_number": 4,
        "title": "Eric",
        "year": 1990,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1377865202l/64218._SY160_.jpg",
        "score": 3.75,
        "pages": 197,
        "isbn": "0380821214"
    },
    {
        "book_number": 25,
        "subseries_id": 6,
        "subseries_number": 2,
        "title": "The Truth",
        "year": 2000,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 4.27,
        "pages": 336,
        "isbn": "0413771164"
    },
    {
        "book_number": 32,
        "subseries_id": 10,
        "subseries_number": 2,
        "title": "A Hat Full of Sky",
        "year": 2004,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1319037274l/34501._SX98_.jpg",
        "score": 4.30,
        "pages": 352,
        "isbn": "055255264X"
    },
    {
        "book_number": 5,
        "subseries_id": 1,
        "subseries_number": 3,
        "title": "Sourcery",
        "year": 1988,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 3.89,
        "pages": 276,
        "isbn": "0061020672"
    },
    {
        "book_number": 20,
        "subseries_id": 3,
        "subseries_number": 4,
        "title": "Hogfather",
        "year": 1996,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1416342611l/34532._SX98_.jpg",
        "score": 4.23,
        "pages": 432,
        "isbn": "0552154288"
    },
    {
        "book_number": 24,
        "subseries_id": 5,
        "subseries_number": 5,
        "title": "The Fifth Elephant",
        "year": 1999,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327961702l/63720._SX98_.jpg",
        "score": 4.27,
        "pages": 464,
        "isbn": "0552154229"
    },
    {
        "book_number": 34,
        "subseries_id": 5,
        "subseries_number": 7,
        "title": "Thud!",
        "year": 2005,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1320495268l/62530._SY160_.jpg",
        "score": 4.33,
        "pages": 439,
        "isbn": "0385608675"
    },
    {
        "book_number": 39,
        "subseries_id": 5,
        "subseries_number": 8,
        "title": "Snuff",
        "year": 2011,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1302694636l/8785374._SX98_.jpg",
        "score": 4.16,
        "pages": 378,
        "isbn": "038561926X"
    },
    {
        "book_number": 38,
        "subseries_id": 10,
        "subseries_number": 4,
        "title": "I Shall Wear Midnight",
        "year": 2010,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1328232764l/7576115._SX98_.jpg",
        "score": 4.35,
        "pages": 349,
        "isbn": "0385611072"
    },
    {
        "book_number": 40,
        "subseries_id": 9,
        "subseries_number": 3,
        "title": "Raising Steam",
        "year": 2013,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1582860489l/11275323._SX98_.jpg",
        "score": 3.98,
        "pages": 377,
        "isbn": "0857522272"
    },
    {
        "book_number": 21,
        "subseries_id": 5,
        "subseries_number": 4,
        "title": "Jingo",
        "year": 1997,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327921813l/47990._SX98_.jpg",
        "score": 4.15,
        "pages": 461,
        "isbn": "0552154164"
    },
    {
        "book_number": 22,
        "subseries_id": 1,
        "subseries_number": 6,
        "title": "The Last Continent",
        "year": 1998,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1332672492l/47994._SX98_.jpg",
        "score": 4.00,
        "pages": 416,
        "isbn": "0552154180"
    },
    {
        "book_number": 16,
        "subseries_id": 3,
        "subseries_number": 3,
        "title": "Soul Music",
        "year": 1994,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 4.04,
        "pages": 424,
        "isbn": "057506689X"
    },
    {
        "book_number": 23,
        "subseries_id": 2,
        "subseries_number": 6,
        "title": "Carpe Jugulum",
        "year": 1998,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 4.15,
        "pages": 296,
        "isbn": "0061051586"
    },
    {
        "book_number": 17,
        "subseries_id": 1,
        "subseries_number": 5,
        "title": "Interesting Times",
        "year": 1994,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1430881376l/884288._SX98_.jpg",
        "score": 4.16,
        "pages": 368,
        "isbn": "0061056901"
    },
    {
        "book_number": 35,
        "subseries_id": 10,
        "subseries_number": 3,
        "title": "Wintersmith",
        "year": 2006,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1290229201l/34492._SX98_.jpg",
        "score": 4.24,
        "pages": 325,
        "isbn": "0060890312"
    },
    {
        "book_number": 18,
        "subseries_id": 2,
        "subseries_number": 5,
        "title": "Maskerade",
        "year": 1995,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 4.09,
        "pages": 285,
        "isbn": "0575058080"
    },
    {
        "book_number": 28,
        "subseries_id": 8,
        "subseries_number": 1,
        "title": "The Amazing Maurice and His Educated Rodents",
        "year": 2001,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 4.05,
        "pages": 256,
        "isbn": "006001234X"
    },
    {
        "book_number": 37,
        "subseries_id": 1,
        "subseries_number": 8,
        "title": "Unseen Academicals",
        "year": 2009,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 3.98,
        "pages": 417,
        "isbn": "0061161705"
    },
    {
        "book_number": 27,
        "subseries_id": 1,
        "subseries_number": 7,
        "title": "The Last Hero",
        "year": 2001,
        "image_url": "https://s.gr-assets.com/assets/nophoto/book/111x148-bcc042a9c91a29c1d680899eff700a03.png",
        "score": 4.17,
        "pages": 176,
        "isbn": "0060507772"
    },
    {
        "book_number": 41,
        "subseries_id": 10,
        "subseries_number": 5,
        "title": "The Shepherd's Crown",
        "year": 2015,
        "image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1433600285l/22886868._SX98_.jpg",
        "score": 4.36,
        "pages": 276,
        "isbn": "0062429973"
    }
]